### ISSUE TITLE
Deploying Office 365 with generated Windows Installer file via Windows 10 MDM fails

### ISSUE THREAD

**Issue by aaronparker** [OfficeDev/Office-IT-Pro-Deployment-Scripts#147]
Using the Install Toolkit to generate a Windows Installer file and deploying that file/app through Windows 10 MDM (via Intune in this case) installs the Windows Installer package OK; however, the custom action for SETUP.EXE fails and Office 365 does not install.

From the log file, it looks like InstallOfficeProPlus.exe is launched but terminated very quickly thereafter. The same installer works when manually running it on the same machine.

Extract from the Windows Installer log below.

```
Action start 10:22:55: InstallFinalize.
SFXCA: Extracting custom action to temporary directory: C:\WINDOWS\Installer\MSI6094.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action Microsoft.OfficeProPlus.MSIGen!CustomActions.InstallOffice
SFXCA: Extracting custom action to temporary directory: C:\WINDOWS\Installer\MSI6160.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action WixSharp!WixSharp.ManagedProjectActions.WixSharp_AfterInstall_Action
Cannot access session details from a non-immediate custom action
Action ended 10:22:56: InstallFinalize. Return value 1.
Action ended 10:22:56: INSTALL. Return value 1.

```

**Comment by pkhabazi** [comment]
We are having  the same problem, the MSI will get installed but Office ProPlus won’t be streamed. However, the older MSI's still work trough Intune deployment. 
When I try to deploy a new MSI trough SCCM/Intune(hybrid) the only difference that I see is the "Installation behavior" which is with a new msi on "Install for system" and with an older MSI its on "Install for user". See this [article ](https://blogs.technet.microsoft.com/home_is_where_i_lay_my_head/2016/04/12/distribute-office-click-to-run-via-microsoft-intune-mdm/)for more information

**Comment by alex182** [comment]
@aaronparker  and @pkhabazi 

We released an updated version of the Install Toolkit yesterday, were you running the most recent version when you had these issues?

**Comment by pkhabazi** [comment]
@alex182 
After installing the new Toolkit I can confirm that the MSI installation trough Intune/SCCM works perfectly again! Thanks for you quick response and the great work!

**Comment by alex182** [comment]
Fantastic!  Please let us know if there are any other issues.  Closing this issue.

**Comment by pkhabazi** [comment]
@alex182  I must  say that the issue is not completely solved. In my test environment where I am using Intune Hybrid with ConfigManager 1606 everything works just fine. However, when we deploy the same MSI on an Intune standalone environment the MSI doesn't get installed at all. We  have studied this specifiek issue in our LAB environment (see our post on [Microsoft  Blog](https://blogs.technet.microsoft.com/home_is_where_i_lay_my_head/2016/08/17/distribute-office-click-to-run-via-microsoft-intune-mdm-part-2/)).

I hope  that the information is useful for resolving this issue, please let me now if we can provide more aid with this issue.

**Comment by aaronparker** [comment]
I haven't had an opportunity to post a log yet, but also seeing issues with Intune stand-alone. Have tested with and without embedded Office source files. Also seeing issues with other MSIs that I would class as complex deployed to Windows 10 via MDM, so I suspect this is more of a Windows 10 issue so unsure whether this can be solved by Office.

In this case, the Office setup.exe is still being terminated early.

**Comment by aaronparker** [comment]
@pkhabazi @alex182 Found this article with a fix; however, I still need to now test: https://blogs.technet.microsoft.com/home_is_where_i_lay_my_head/2016/08/17/distribute-office-click-to-run-via-microsoft-intune-mdm-part-2/

**Comment by johnskydiver** [comment]
I was able to test the issue, I'm not sure if it's limited to Windows 10 or not, however, apparently MDM can be very picky.  I was able to correct the issue by removing the "allusers" property from the generated MSI, and have confirmed that this has fixed the issue.  The fix for this will be made available for download by the end of this week.  Thank you for your patience and your feedback.

**Comment by aaronparker** [comment]
Thanks @johnskydiver. Very much appreciated.
